

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
                ref class Button;
                ref class ComboBox;
                ref class StackPanel;
                ref class ComboBoxItem;
                ref class TextBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}

namespace SDKSample
{
    namespace Tiles
    {
        partial ref class SendBadge : public ::Windows::UI::Xaml::Controls::Page, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
            private: ::Windows::UI::Xaml::Controls::Grid^ Input;
            private: ::Windows::UI::Xaml::Controls::Grid^ Output;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ OutputTextBlock;
            private: ::Windows::UI::Xaml::Controls::Button^ UpdateBadgeWithStringManipulation;
            private: ::Windows::UI::Xaml::Controls::Button^ UpdateBadge;
            private: ::Windows::UI::Xaml::Controls::Button^ ClearBadge;
            private: ::Windows::UI::Xaml::Controls::ComboBox^ NumberOrGlyph;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ NumberPanel;
            private: ::Windows::UI::Xaml::Controls::StackPanel^ GlyphPanel;
            private: ::Windows::UI::Xaml::Controls::ComboBox^ GlyphList;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ none;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ activity;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ alert;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ available;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ away;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ busy;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ newMessage;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ paused;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ playing;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ unavailable;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ error;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ attention;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ alarm;
            private: ::Windows::UI::Xaml::Controls::TextBox^ NumberInput;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Number;
            private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Glyph;
            private: ::Windows::UI::Xaml::VisualState^ DefaultLayout;
            private: ::Windows::UI::Xaml::VisualState^ Below768Layout;
        };
    }
}

