

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Scenario6_EnableNotificationQueue.xaml.h"




void ::SDKSample::Tiles::EnableNotificationQueue::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Scenario6_EnableNotificationQueue.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Scenario6_EnableNotificationQueue.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'LayoutRoot'
    LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LayoutRoot"));
    // Get the Grid named 'Input'
    Input = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Input"));
    // Get the Grid named 'Output'
    Output = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Output"));
    // Get the TextBlock named 'OutputTextBlock'
    OutputTextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"OutputTextBlock"));
    // Get the Button named 'UpdateTile'
    UpdateTile = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"UpdateTile"));
    // Get the Button named 'ClearTile'
    ClearTile = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ClearTile"));
    // Get the TextBox named 'Id'
    Id = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Id"));
    // Get the TextBox named 'TextContent'
    TextContent = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TextContent"));
    // Get the Button named 'EnableSquare310x310NotificationQueue'
    EnableSquare310x310NotificationQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EnableSquare310x310NotificationQueue"));
    // Get the Button named 'DisableSquare310x310NotificationQueue'
    DisableSquare310x310NotificationQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DisableSquare310x310NotificationQueue"));
    // Get the Button named 'EnableWide310x150NotificationQueue'
    EnableWide310x150NotificationQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EnableWide310x150NotificationQueue"));
    // Get the Button named 'DisableWide310x150NotificationQueue'
    DisableWide310x150NotificationQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DisableWide310x150NotificationQueue"));
    // Get the Button named 'EnableSquare150x150NotificationQueue'
    EnableSquare150x150NotificationQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EnableSquare150x150NotificationQueue"));
    // Get the Button named 'DisableSquare150x150NotificationQueue'
    DisableSquare150x150NotificationQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DisableSquare150x150NotificationQueue"));
    // Get the Button named 'EnableQueue'
    EnableQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EnableQueue"));
    // Get the Button named 'DisableQueue'
    DisableQueue = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DisableQueue"));
    // Get the VisualState named 'DefaultLayout'
    DefaultLayout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DefaultLayout"));
    // Get the VisualState named 'Below768Layout'
    Below768Layout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Below768Layout"));
}

void ::SDKSample::Tiles::EnableNotificationQueue::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::UpdateTile_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::ClearTile_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::EnableSquare310x310NotificationQueue_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::DisableSquare310x310NotificationQueue_Click);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::EnableWide310x150NotificationQueue_Click);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::DisableWide310x150NotificationQueue_Click);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::EnableSquare150x150NotificationQueue_Click);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::DisableSquare150x150NotificationQueue_Click);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::EnableNotificationQueue_Click);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::EnableNotificationQueue::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&EnableNotificationQueue::DisableNotificationQueue_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

