

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Scenario4_SendBadge.xaml.h"




void ::SDKSample::Tiles::SendBadge::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Scenario4_SendBadge.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Scenario4_SendBadge.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'LayoutRoot'
    LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LayoutRoot"));
    // Get the Grid named 'Input'
    Input = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Input"));
    // Get the Grid named 'Output'
    Output = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Output"));
    // Get the TextBlock named 'OutputTextBlock'
    OutputTextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"OutputTextBlock"));
    // Get the Button named 'UpdateBadgeWithStringManipulation'
    UpdateBadgeWithStringManipulation = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"UpdateBadgeWithStringManipulation"));
    // Get the Button named 'UpdateBadge'
    UpdateBadge = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"UpdateBadge"));
    // Get the Button named 'ClearBadge'
    ClearBadge = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ClearBadge"));
    // Get the ComboBox named 'NumberOrGlyph'
    NumberOrGlyph = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"NumberOrGlyph"));
    // Get the StackPanel named 'NumberPanel'
    NumberPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"NumberPanel"));
    // Get the StackPanel named 'GlyphPanel'
    GlyphPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"GlyphPanel"));
    // Get the ComboBox named 'GlyphList'
    GlyphList = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"GlyphList"));
    // Get the ComboBoxItem named 'none'
    none = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"none"));
    // Get the ComboBoxItem named 'activity'
    activity = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"activity"));
    // Get the ComboBoxItem named 'alert'
    alert = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"alert"));
    // Get the ComboBoxItem named 'available'
    available = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"available"));
    // Get the ComboBoxItem named 'away'
    away = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"away"));
    // Get the ComboBoxItem named 'busy'
    busy = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"busy"));
    // Get the ComboBoxItem named 'newMessage'
    newMessage = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"newMessage"));
    // Get the ComboBoxItem named 'paused'
    paused = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"paused"));
    // Get the ComboBoxItem named 'playing'
    playing = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"playing"));
    // Get the ComboBoxItem named 'unavailable'
    unavailable = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"unavailable"));
    // Get the ComboBoxItem named 'error'
    error = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"error"));
    // Get the ComboBoxItem named 'attention'
    attention = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"attention"));
    // Get the ComboBoxItem named 'alarm'
    alarm = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"alarm"));
    // Get the TextBox named 'NumberInput'
    NumberInput = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"NumberInput"));
    // Get the ComboBoxItem named 'Number'
    Number = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Number"));
    // Get the ComboBoxItem named 'Glyph'
    Glyph = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Glyph"));
    // Get the VisualState named 'DefaultLayout'
    DefaultLayout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DefaultLayout"));
    // Get the VisualState named 'Below768Layout'
    Below768Layout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Below768Layout"));
}

void ::SDKSample::Tiles::SendBadge::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::SendBadge::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&SendBadge::UpdateBadge_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::SendBadge::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&SendBadge::UpdateBadge_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::SendBadge::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&SendBadge::ClearBadge_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::SDKSample::Tiles::SendBadge::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&SendBadge::NumberOrGlyph_SelectionChanged);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

