

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Scenario8_ImageProtocols.xaml.h"




void ::SDKSample::Tiles::ImageProtocols::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Scenario8_ImageProtocols.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Scenario8_ImageProtocols.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'LayoutRoot'
    LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LayoutRoot"));
    // Get the Grid named 'Input'
    Input = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Input"));
    // Get the Grid named 'Output'
    Output = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Output"));
    // Get the TextBlock named 'OutputTextBlock'
    OutputTextBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"OutputTextBlock"));
    // Get the ComboBox named 'ProtocolList'
    ProtocolList = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ProtocolList"));
    // Get the StackPanel named 'LocalFolder'
    LocalFolder = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LocalFolder"));
    // Get the StackPanel named 'HTTP'
    HTTP = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HTTP"));
    // Get the Button named 'SendTileNotification'
    SendTileNotification = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"SendTileNotification"));
    // Get the TextBox named 'HTTPImage5'
    HTTPImage5 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HTTPImage5"));
    // Get the TextBox named 'HTTPImage4'
    HTTPImage4 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HTTPImage4"));
    // Get the TextBox named 'HTTPImage3'
    HTTPImage3 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HTTPImage3"));
    // Get the TextBox named 'HTTPImage2'
    HTTPImage2 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HTTPImage2"));
    // Get the TextBox named 'HTTPImage1'
    HTTPImage1 = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HTTPImage1"));
    // Get the TextBox named 'HTTPBaseURI'
    HTTPBaseURI = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HTTPBaseURI"));
    // Get the Button named 'PickImage'
    PickImage = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PickImage"));
    // Get the ComboBoxItem named 'package'
    package = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"package"));
    // Get the ComboBoxItem named 'appdata'
    appdata = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"appdata"));
    // Get the ComboBoxItem named 'http'
    http = safe_cast<::Windows::UI::Xaml::Controls::ComboBoxItem^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"http"));
    // Get the VisualState named 'DefaultLayout'
    DefaultLayout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"DefaultLayout"));
    // Get the VisualState named 'Below768Layout'
    Below768Layout = safe_cast<::Windows::UI::Xaml::VisualState^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Below768Layout"));
}

void ::SDKSample::Tiles::ImageProtocols::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::SDKSample::Tiles::ImageProtocols::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&ImageProtocols::ProtocolList_SelectionChanged);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::ImageProtocols::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ImageProtocols::SendTileNotification_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SDKSample::Tiles::ImageProtocols::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ImageProtocols::PickImage_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

