

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
                ref class Button;
                ref class TextBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}

namespace SDKSample
{
    namespace Tiles
    {
        partial ref class EnableNotificationQueue : public ::Windows::UI::Xaml::Controls::Page, 
            public ::Windows::UI::Xaml::Markup::IComponentConnector
        {
        public:
            void InitializeComponent();
            virtual void Connect(int connectionId, ::Platform::Object^ target);
        
        private:
            bool _contentLoaded;
        
            private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
            private: ::Windows::UI::Xaml::Controls::Grid^ Input;
            private: ::Windows::UI::Xaml::Controls::Grid^ Output;
            private: ::Windows::UI::Xaml::Controls::TextBlock^ OutputTextBlock;
            private: ::Windows::UI::Xaml::Controls::Button^ UpdateTile;
            private: ::Windows::UI::Xaml::Controls::Button^ ClearTile;
            private: ::Windows::UI::Xaml::Controls::TextBox^ Id;
            private: ::Windows::UI::Xaml::Controls::TextBox^ TextContent;
            private: ::Windows::UI::Xaml::Controls::Button^ EnableSquare310x310NotificationQueue;
            private: ::Windows::UI::Xaml::Controls::Button^ DisableSquare310x310NotificationQueue;
            private: ::Windows::UI::Xaml::Controls::Button^ EnableWide310x150NotificationQueue;
            private: ::Windows::UI::Xaml::Controls::Button^ DisableWide310x150NotificationQueue;
            private: ::Windows::UI::Xaml::Controls::Button^ EnableSquare150x150NotificationQueue;
            private: ::Windows::UI::Xaml::Controls::Button^ DisableSquare150x150NotificationQueue;
            private: ::Windows::UI::Xaml::Controls::Button^ EnableQueue;
            private: ::Windows::UI::Xaml::Controls::Button^ DisableQueue;
            private: ::Windows::UI::Xaml::VisualState^ DefaultLayout;
            private: ::Windows::UI::Xaml::VisualState^ Below768Layout;
        };
    }
}

